databases:
  - name: ctlms-db
    plan: free
    databaseName: ctlms
    user: ctlms_user

services:
  - type: web
    plan: free
    name: ctlms
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn ctlms.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ctlms-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: RENDER
        value: true
      - key: DEBUG
        value: false
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@gmail.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: admin
